version: "2"
services:
  app:
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.2
    environment:
      - ES_JAVA_OPTS=-Xmx700m -Xms700m
      - http.host=0.0.0.0
    ports:
      - 9200:9200

